### Домашняя работа по теме “Вычисления с помощью Numpy”

Задание 1.

In [1]:
import numpy as np

In [2]:
a = np.array([[1,6], [2,8], [3,11], [3,10], [1,7]]) # исходный массив
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.array([a[0:, 0].mean(), a[0:, 1].mean()]) # вычисление среднего значения по каждому столбцу
mean_a

array([2. , 8.4])

Задание 2.

In [4]:
a_centered = a - mean_a # отнимаем у каждого признака среднее значение столбца
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3.

In [5]:
N = a.shape[0] #количество наблюдений
a_centered_sp = np.dot(a_centered[0:, 0], a_centered[0:, 1]) # скалярное произведение двух столбцов массива a_centered
a_centered_sp

8.0

In [6]:
res = a_centered_sp / (N-1) # значение ковариации двух признаков
res

2.0

Задание 4. 

In [7]:
another_way = np.cov(a.transpose()) # альтернативный метод нахождения ковариации
result = another_way[0,1] # результатом является элемент, находящийся на позиции в первой строке и втором столбце
result

2.0

### Домашняя работа по теме “Работа с данными в Pandas”

Задание 1.

In [8]:
import pandas as pd

In [9]:
# создание таблицы "Авторы"
authors = pd.DataFrame(
    {"author_id": [1,2,3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']}
)

# создание таблицы "Книги"
books = pd.DataFrame(
    {"author_id": [1, 1, 1, 2, 2, 3, 3],
     "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой',
                    'Гроза', 'Таланты и поклонники'],
     "price": [450, 300, 350, 500, 450, 370, 290]}
)

print(authors)
print(books)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


Задание 2.

In [10]:
# Объединение двух таблиц "Авторы" и "Книги" по author_id
authors_price = pd.merge(authors, books, on="author_id", how="inner")
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


Задание 3.

In [11]:
# Нахождение книг по максимальной цене, вывод только 5 книг
top5 = authors_price.nlargest(5, "price")
print(top5)

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350


Задание 4.

In [12]:
# Группировка по author_id
groupby =  authors_price.groupby("author_id")

# Формирование таблицы, в которой представлен автор, минимальная цена его книги, максимальная и средняя.
authors_stat = pd.DataFrame({
    "author_name": list(authors.values[0:,1]),
    "min_price": list(groupby["price"].min()),
    "max_price": list(groupby["price"].max()),
    "mean_price": list(groupby["price"].mean())

})

print(authors_stat)

  author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000


Задание 5.

In [13]:
# Добавление дополнительного поля
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
print(authors_price)

   author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая


In [14]:
# Формирование таблицы с группировкой по имени автора, по типу обложки
# и представлении сведений о максимальной, минимальной и средней цене.

book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc={'price': [min, max, np.mean]}, fill_value=0)
print(book_info)

               max           mean            min        
cover       мягкая твердая мягкая твердая мягкая твердая
author_name                                             
Островский     370       0    330       0    290       0
Тургенев       350     450    325     450    300     450
Чехов            0     500      0     475      0     450


In [15]:
# Сохранение таблицы book_info

book_info.to_pickle("book_info.pkl")

# Загрузка таблицы из файла

book_info2 = pd.read_pickle("book_info.pkl")
print(book_info2)

               max           mean            min        
cover       мягкая твердая мягкая твердая мягкая твердая
author_name                                             
Островский     370       0    330       0    290       0
Тургенев       350     450    325     450    300     450
Чехов            0     500      0     475      0     450
